openapi: 3.1.0
info:
  title: A2AChat API
  version: 1.0.0
  description: Agent 간 상호작용을 위한 API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /api/v1
    description: API 서버

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /agents:
    $ref: './paths/agents.yaml'
  /agents/{agentId}:
    $ref: './paths/agents-:agentId.yaml'
  /mcps:
    $ref: './paths/mcps.yaml'
  /mcps/{mcpId}:
    $ref: './paths/mcps-:mcpId.yaml'
  /schedules:
    $ref: './paths/schedules.yaml'
  /schedules/{scheduleId}:
    $ref: './paths/schedules-:scheduleId.yaml'
  /chat:
    $ref: './paths/chat.yaml'
  /chat/history:
    $ref: './paths/chat-history.yaml' 