version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: a2achat-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - a2achat-network

  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: a2achat-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/a2achat?authSource=admin
    depends_on:
      - mongodb
    networks:
      - a2achat-network

volumes:
  mongodb_data:

networks:
  a2achat-network:
    driver: bridge 